image: "scorpil/rust:stable"

# Not sure why this is needed, but it is
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

# Use cargo to test the project
test:cargo:
  script:
  - mkdir -p target
  - mkdir -p cargo
  - du -hs target
  - du -hs cargo
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --verbose --jobs 1 --release # Don't paralize to make errors more readable
  cache:
    paths:
    - target/
    - cargo/
    
pages:
  only:
  - master
  script:
  - cargo doc
  - rm -rf public
  - mkdir public
  - cp -R target/doc/* public
  artifacts:
    paths:
    - public
  cache:
    paths:
    - target/
    - cargo/