[package]
name = "aspen"
version = "0.2.3"
authors = ["Nathan Kent <nate@nkent.net>"]
license = "MIT"

description = "A behavior tree implementation in Rust"
keywords = ["behavior", "tree", "fsm", "state", "ai"]

documentation = "https://docs.rs/aspen"
repository = "https://gitlab.com/neachdainn/aspen.git"

readme = "README.adoc"

build = "build.rs"

[features]
default = []

[dependencies]
lcm = { version = "0.1.0", optional = true }

[build-dependencies]
lcm_gen = "0.1.0"
