[package]
name = "aspen"
version = "0.2.2"
authors = ["Nathan Kent <nate@nkent.net>"]
license = "MIT"

description = "A behavior tree implementation in Rust"
keywords = ["behavior", "tree", "fsm", "state", "ai"]

documentation = "http://neachdainn.gitlab.io/aspen"
repository = "https://gitlab.com/neachdainn/aspen.git"

readme = "README.adoc"

build = "build.rs"

[features]
default = []

[dependencies]
lcm = { git = "https://github.com/adeschamps/lcm.git", rev = "cd03122", optional = true }

[build-dependencies]
lcm_gen = { git = "https://github.com/adeschamps/lcm.git", rev = "cd03122" }
