[package]
name = "aspen"
version = "0.1.0"
authors = ["Nathan Kent <nate@nkent.net>"]
license = "MIT"

description = "A behavior tree implementation in Rust"

documentation = "http://neachdainn.gitlab.io/aspen"
repository = "https://gitlab.com/neachdainn/aspen.git"

readme = "README.adoc"

publish = false

build = "build.rs"

[features]
default = []

messages = ["lcm"]

[dependencies]
lcm = { git = "https://github.com/adeschamps/lcm.git", rev = "cd03122", optional = true }

[build-dependencies]
lcm_gen = { git = "https://github.com/adeschamps/lcm.git", rev = "cd03122" }
